[package]
authors = ["J David Smith <emallson@atlanis.net>"]
name = "ris"
version = "0.1.0"
license = "BSD-3-Clause"

[dependencies]
bit-set = "0.4.0"
rand = "0.3.15"
rayon = "0.6.0"

[dev-dependencies]
quickcheck = "0.4.1"

[dependencies.petgraph]
version = "0.4.3"
features = ["quickcheck"]
