[package]
authors = ["J David Smith <emallson@atlanis.net>"]
license = "BSD-3-Clause"
name = "ris"
version = "0.1.0"

[[bench]]
harness = false
name = "ris"

[dependencies]
bit-set = "0.4.0"
rand = "0.3.15"
rayon = "0.8"

[dependencies.petgraph]
features = ["quickcheck"]
version = "0.4.7"

[dependencies.vec-graph]
git = "https://github.com/emallson/vec-graph.git"
optional = false

[dev-dependencies]
bencher = "0.1.2"
quickcheck = "0.4.1"

