[package]
authors = ["J David Smith <emallson@atlanis.net>"]
license = "BSD-3-Clause"
name = "ris"
version = "0.1.0"

[dependencies]
as_num = "0.2.3"
bit-set = "0.4.0"
rand = "0.3.15"
rayon = "0.8"

[dependencies.fnv]
optional = true
version = "1.0.5"

[dependencies.petgraph]
features = ["quickcheck"]
version = "0.4.7"

[dependencies.vec-graph]
git = "https://github.com/emallson/vec-graph.git"
optional = false

[dev-dependencies]
quickcheck = "0.4.1"

[features]
hash = ["fnv"]
